# Generated by Django 6.0.5 on 2026-05-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='BOLETA', max_length=20)),
                ('serie', models.CharField(default='B001', max_length=4)),
                ('correlativo', models.CharField(max_length=8)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('igv', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cliente_nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
