# Generated by Django 6.0.5 on 2026-05-24 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimiento', '0002_rename_rubro_proveedor_categoria_proveedor_contacto_and_more'),
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='categoria',
            field=models.CharField(default='Otros', max_length=50),
        ),
        migrations.AddField(
            model_name='insumo',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='insumo',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abastecimiento.proveedor'),
        ),
        migrations.AddField(
            model_name='movimientoalmacen',
            name='area_destino',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movimientoalmacen',
            name='guia_remision',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movimientoalmacen',
            name='motivo_merma',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movimientoalmacen',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientoalmacen',
            name='operario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(default='kg', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimientoalmacen',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('MERMA', 'Merma')], max_length=15),
        ),
    ]
